((nil . ((indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 80)))
 (cperl-mode . ((cperl-indent-level . 4)
                (cperl-extra-newline-before-brace . t)
                (cperl-merge-trailing-else . nil))))
