((nil . ((indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 80)))
 (makefile-mode . ((indent-tabs-mode . t)))
 (cperl-mode . ((cperl-indent-level . 4)
                (cperl-brace-offset . 0)
                (cperl-close-paren-offset . -1)
                (cperl-brace-imaginary-offset . 0)
                (cperl-continued-brace-offset . 0)
                (cperl-continued-statement-offset . 0)
                (cperl-fix-hanging-brace-when-indent . t)
                (cperl-extra-newline-before-brace . t)
                (cperl-merge-trailing-else . nil))))
