---
abstract: 'Micro Objects. Mo is less.'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Mo
name: Mo
no_index:
  directory:
    - inc
    - src
    - t
    - xt
recommends:
  Class::XSAccessor: 0
  IO::All: 0
  Moose: 0
  Mouse: 0
requires:
  perl: 5.6.0
resources:
  homepage: https://github.com/ingydotnet/mo-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/mo-pm.git
    web: https://github.com/ingydotnet/mo-pm/tree
version: 0.31
