--- #YAML:1.0
name:               File-Path
version:            2.09
abstract:           Create or remove directory trees
author:
    - David Landgren
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Cwd:             0
    File::Basename:  0
    File::Spec:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
