#!/bin/sh

#./cat.sh 29
time ./cat.sh

time a2x -v \
    -a docinfo2 \
    -f pdf \
    --fop \
    --xsltproc-opts="--stringparam toc.section.depth 0 --stringparam  section.autolabel 0 --stringparam  generate.toc \"book toc\" --stringparam page.orientation landscape" \
    -d book ebook.txt | \
  remark ./xmllint.remark && \
evince  ebook.pdf
